version: '3.0'

services:
  projectx:
    image: projectx:latest
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/work # source code
    command: python3 main.py  # start main.py
